export const WALLET_CONNECT_KEY = 'walletconnect';
export const WALLET_CONNECT_DEEPLINK_KEY = 'WALLETCONNECT_DEEPLINK_CHOICE';
export const CONNECTED_POLKA_WALLET_KEY = 'CONNECTED_POLKA_WALLET';
export const CONNECTED_EVM_WALLET_KEY = 'CONNECTED_EVM_WALLET';
export const AUTH_TOKEN_KEY = 'AUTH_TOKEN';
