name: Deploy Prod

on:
  workflow_dispatch:

env:
  ECR: 081239602556.dkr.ecr.eu-central-1.amazonaws.com/polkapad-polkapad-app
  ROLE: "arn:aws:iam::081239602556:role/github-ecr-polkapad-polkapad-app"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo
    steps:
      - uses: actions/checkout@v3

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1
        #if: ${{ github.event_name == 'push' }}

      - name: Set env
        run: |
          echo "TAG=${ECR}:${{ env.GIT_COMMIT_SHORT_SHA }}" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'

      - name: Update npm
        run: npm install -g npm@8.12.1

      - name: Install dependencies
        run: npm ci

      - name: Docker build
        run: >
          docker build -t $TAG
          --build-arg GOOGLE_ANALYTICS_ID="${{ secrets.GOOGLE_ANALYTICS_ID_PROD }}"
          --build-arg SECRET_COOKIE_PASSWORD="${{ secrets.PROD_SECRET_COOKIE_PASSWORD }}"
          --build-arg SERVICE_URL="${{ secrets.SERVICE_URL_PROD }}"
          --build-arg SENTRY_DSN="${{ secrets.SENTRY_DSN }}"
          --build-arg FACEBOOK_PIXEL="${{ secrets.FACEBOOK_PIXEL }}"
          --build-arg FACEBOOK_VERIFY_ID="${{ secrets.FACEBOOK_VERIFY_ID }}"
          --build-arg SENTRY_AUTH_TOKEN="${{ secrets.SENTRY_AUTH_TOKEN }}"
          --build-arg MAILCHIMP_ID="${{ secrets.PROD_MAILCHIMP_ID }}"
          --build-arg ENVIRONMENT="PRODUCTION"
          -f .github/workflows/Dockerfile .

      - name: Push to ECR and Argo
        uses: ./.github/actions/argo-push
        with:
          aws-role: ${{ env.ROLE }}
          aws-ecr-uri: ${{ env.ECR }}
          ssh-key: ${{ secrets.ARGOCD_REPO_SSH }}
          environment: prod
          project: polkapad_app
          image: ${{ env.TAG }}

